/**
 * Curated list of ~500 global company names including Fortune 500,
 * major tech companies, unicorns, financial institutions, and more.
 * Used for client-side autocomplete in the Role Catalog search.
 */
export const COMPANY_NAMES: string[] = [
  // ─── BIG TECH / FAANG ───────────────────────────────────────────────────────
  'Apple',
  'Google',
  'Alphabet',
  'Meta',
  'Amazon',
  'Microsoft',
  'Netflix',
  'Google DeepMind',

  // ─── MAJOR TECH ─────────────────────────────────────────────────────────────
  'Salesforce',
  'Oracle',
  'IBM',
  'Cisco',
  'Intel',
  'AMD',
  'NVIDIA',
  'Qualcomm',
  'Adobe',
  'SAP',
  'Workday',
  'ServiceNow',
  'Palantir',
  'Palantir Technologies',
  'Snowflake',
  'Databricks',
  'MongoDB',
  'Elastic',
  'HashiCorp',
  'Confluent',
  'Cloudflare',
  'Fastly',
  'Okta',
  'CrowdStrike',
  'Palo Alto Networks',
  'Splunk',
  'New Relic',
  'Datadog',
  'PagerDuty',
  'Twilio',
  'Stripe',
  'Square',
  'Block',
  'Plaid',
  'Brex',
  'Ramp',
  'Chime',
  'Robinhood',
  'Coinbase',
  'Ripple',
  'Chainalysis',
  'Figma',
  'Miro',
  'Notion',
  'Airtable',
  'Linear',
  'Vercel',
  'Netlify',
  'Supabase',
  'PlanetScale',
  'Railway',
  'DigitalOcean',
  'Linode',
  'Fly.io',
  'Render',
  'Heroku',
  'Segment',
  'Amplitude',
  'Mixpanel',
  'Heap',
  'FullStory',
  'Hotjar',
  'Contentful',
  'Sanity',
  'Strapi',
  'Ghost',
  'Webflow',
  'Wix',
  'Squarespace',
  'Shopify',
  'BigCommerce',
  'WooCommerce',
  'Klaviyo',
  'Mailchimp',
  'HubSpot',
  'Zendesk',
  'Intercom',
  'Freshworks',
  'Zoho',
  'Atlassian',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'Slack',
  'Zoom',
  'Loom',
  'Calendly',
  'Asana',
  'Monday.com',
  'Jira',
  'Trello',
  'Basecamp',
  'ClickUp',

  // ─── AI & FRONTIER TECH ─────────────────────────────────────────────────────
  'OpenAI',
  'Anthropic',
  'Cohere',
  'Mistral AI',
  'Hugging Face',
  'Scale AI',
  'Weights & Biases',
  'Stability AI',
  'Midjourney',
  'Runway',
  'ElevenLabs',
  'Deepgram',
  'Grammarly',
  'Jasper',
  'Writer',
  'Character.AI',
  'Inflection AI',
  'AI21 Labs',
  'Perplexity AI',
  'Replit',
  'GitHub Copilot',
  'Anduril Industries',

  // ─── CLOUD PROVIDERS ────────────────────────────────────────────────────────
  'Amazon Web Services',
  'Google Cloud',
  'Microsoft Azure',
  'Alibaba Cloud',
  'Oracle Cloud',

  // ─── UNICORNS / GROWTH STARTUPS ─────────────────────────────────────────────
  'Uber',
  'Lyft',
  'Airbnb',
  'DoorDash',
  'Instacart',
  'Gopuff',
  'Grubhub',
  'Postmates',
  'Coupang',
  'Grab',
  'Gojek',
  'Rappi',
  'iFood',
  'Delivery Hero',
  'Just Eat Takeaway',
  'Glovo',
  'Deliveroo',
  'Swiggy',
  'Zomato',
  'OYO',
  'Didi',
  'Meituan',
  'ByteDance',
  'TikTok',
  'Xiaomi',
  'Klarna',
  'Affirm',
  'Afterpay',
  'Toast',
  'Bill.com',
  'Marqeta',
  'Adyen',
  'Checkout.com',
  'Nubank',
  'Revolut',
  'Wise',
  'N26',
  'Monzo',
  'Starling Bank',
  'Nuvei',

  // ─── FINANCE / BANKING ──────────────────────────────────────────────────────
  'Goldman Sachs',
  'JPMorgan Chase',
  'Morgan Stanley',
  'Citigroup',
  'Bank of America',
  'Wells Fargo',
  'Barclays',
  'Deutsche Bank',
  'UBS',
  'HSBC',
  'BNP Paribas',
  'Société Générale',
  'Nomura',
  'Standard Chartered',
  'ING Group',
  'Santander',
  'Lloyds Banking Group',
  'Royal Bank of Canada',
  'TD Bank',
  'Scotiabank',
  'BMO Financial',
  'Capital One',
  'American Express',
  'Discover Financial',
  'Synchrony Financial',
  'Ally Financial',
  'Visa',
  'Mastercard',
  'PayPal',

  // ─── ASSET MANAGEMENT & TRADING ─────────────────────────────────────────────
  'BlackRock',
  'Vanguard',
  'Fidelity Investments',
  'State Street',
  'T. Rowe Price',
  'Franklin Templeton',
  'Invesco',
  'PIMCO',
  'Wellington Management',
  'Bridgewater Associates',
  'Renaissance Technologies',
  'Two Sigma',
  'Citadel',
  'Point72',
  'D.E. Shaw',
  'Jane Street',
  'Susquehanna International Group',
  'Virtu Financial',
  'Jump Trading',
  'Hudson River Trading',
  'Akuna Capital',
  'DRW',
  'IMC Trading',
  'Flow Traders',

  // ─── CONSULTING ─────────────────────────────────────────────────────────────
  'McKinsey & Company',
  'Boston Consulting Group',
  'BCG',
  'Bain & Company',
  'Deloitte',
  'PricewaterhouseCoopers',
  'PwC',
  'Ernst & Young',
  'EY',
  'KPMG',
  'Accenture',
  'Oliver Wyman',
  'Roland Berger',
  'LEK Consulting',
  'A.T. Kearney',
  'Kearney',
  'Alvarez & Marsal',
  'FTI Consulting',
  'Booz Allen Hamilton',
  'Leidos',
  'SAIC',
  'Gartner',
  'Forrester',
  'IDC',

  // ─── HEALTHCARE / PHARMA / BIOTECH ──────────────────────────────────────────
  'Johnson & Johnson',
  'Pfizer',
  'Moderna',
  'AstraZeneca',
  'Roche',
  'Novartis',
  'Merck',
  'Abbott Laboratories',
  'Medtronic',
  'Boston Scientific',
  'Stryker',
  'Becton Dickinson',
  'Baxter International',
  'Edwards Lifesciences',
  'Intuitive Surgical',
  'GE Healthcare',
  'Philips Healthcare',
  'Siemens Healthineers',
  'Illumina',
  'IQVIA',
  'LabCorp',
  'Quest Diagnostics',
  'UnitedHealth Group',
  'Anthem',
  'Cigna',
  'Aetna',
  'Humana',
  'CVS Health',
  'Walgreens',
  'McKesson',
  'Cardinal Health',
  'Kaiser Permanente',
  'Mayo Clinic',
  'Cleveland Clinic',
  'Johns Hopkins Medicine',
  'Eli Lilly',
  'Bristol Myers Squibb',
  'GlaxoSmithKline',
  'GSK',
  'Sanofi',
  'Amgen',
  'Gilead Sciences',
  'Regeneron Pharmaceuticals',
  'Vertex Pharmaceuticals',
  'Biogen',
  'Genentech',
  'Alnylam Pharmaceuticals',

  // ─── RETAIL / E-COMMERCE ────────────────────────────────────────────────────
  'Walmart',
  'Target',
  'Costco',
  'Kroger',
  'Home Depot',
  "Lowe's",
  'Best Buy',
  'TJX Companies',
  'Ross Stores',
  'Gap',
  'H&M',
  'Zara',
  'Inditex',
  'UNIQLO',
  'Fast Retailing',
  'LVMH',
  'Kering',
  'Hermès',
  'Richemont',
  'Tapestry',
  'Nordstrom',
  "Macy's",
  "Kohl's",
  'Dollar General',
  'Dollar Tree',
  'Five Below',
  'Chewy',
  'Etsy',
  'Wayfair',
  'Farfetch',
  'Revolve',
  'ASOS',
  'Zalando',
  'eBay',
  'Alibaba',
  'JD.com',
  'Rakuten',

  // ─── CONSUMER GOODS ─────────────────────────────────────────────────────────
  'Procter & Gamble',
  'Unilever',
  'Nestlé',
  'Coca-Cola',
  'PepsiCo',
  'Mondelez',
  'Kraft Heinz',
  'Mars',
  'Colgate-Palmolive',
  'Kimberly-Clark',
  'Church & Dwight',
  'Reckitt',
  'AB InBev',
  'Diageo',
  'Pernod Ricard',
  "Constellation Brands",
  'Molson Coors',

  // ─── FOOD & RESTAURANTS ─────────────────────────────────────────────────────
  "McDonald's",
  'Starbucks',
  "Yum! Brands",
  'Restaurant Brands International',
  'Chipotle',
  'Shake Shack',
  'Darden Restaurants',
  "Domino's",
  "Papa John's",
  'Wingstop',

  // ─── AUTOMOTIVE ─────────────────────────────────────────────────────────────
  'Tesla',
  'Ford Motor Company',
  'General Motors',
  'Toyota',
  'Volkswagen',
  'BMW',
  'Mercedes-Benz',
  'Stellantis',
  'Honda',
  'Hyundai',
  'Rivian',
  'Lucid Motors',
  'Fisker',
  'Waymo',
  'Cruise',
  'Mobileye',
  'Aptiv',
  'BorgWarner',
  'Denso',
  'Bosch',

  // ─── AEROSPACE & DEFENSE ────────────────────────────────────────────────────
  'Lockheed Martin',
  'Boeing',
  'Raytheon Technologies',
  'Northrop Grumman',
  'General Dynamics',
  'L3Harris Technologies',
  'BAE Systems',
  'Airbus',
  'Thales',
  'SpaceX',
  'Blue Origin',
  'Rocket Lab',
  'Aerojet Rocketdyne',

  // ─── ENERGY ─────────────────────────────────────────────────────────────────
  'ExxonMobil',
  'Chevron',
  'Shell',
  'BP',
  'TotalEnergies',
  'ConocoPhillips',
  'Occidental Petroleum',
  'NextEra Energy',
  'Duke Energy',
  'Southern Company',
  'Dominion Energy',
  'Exelon',
  'Consolidated Edison',
  'Pacific Gas & Electric',
  'PG&E',
  'Orsted',
  'Vestas',
  'SolarEdge',
  'Enphase Energy',
  'First Solar',

  // ─── TELECOM ────────────────────────────────────────────────────────────────
  'AT&T',
  'Verizon',
  'T-Mobile',
  'Comcast',
  'Charter Communications',
  'Vodafone',
  'Deutsche Telekom',
  'Orange',
  'Telefónica',
  'BT Group',
  'SoftBank',
  'NTT',
  'SK Telecom',

  // ─── MEDIA & ENTERTAINMENT ──────────────────────────────────────────────────
  'Disney',
  'Warner Bros. Discovery',
  'Paramount Global',
  'NBCUniversal',
  'Sony',
  'Spotify',
  'iHeartMedia',
  'Endeavor',
  'Creative Artists Agency',
  'CAA',
  'William Morris Endeavor',
  'WME',

  // ─── REAL ESTATE & FINANCE ──────────────────────────────────────────────────
  'CBRE',
  'JLL',
  'Cushman & Wakefield',
  'Colliers',
  'Brookfield Asset Management',
  'Blackstone',
  'KKR',
  'Apollo Global Management',
  'Carlyle Group',
  'TPG',
  'Warburg Pincus',
  'General Atlantic',
  'Andreessen Horowitz',
  'Sequoia Capital',
  'Benchmark Capital',
  'Accel',
  'Index Ventures',
  'Lightspeed Venture Partners',

  // ─── SUPPLY CHAIN & LOGISTICS ───────────────────────────────────────────────
  'UPS',
  'FedEx',
  'DHL',
  'XPO Logistics',
  'J.B. Hunt',
  'C.H. Robinson',
  'Expeditors International',
  'Kuehne + Nagel',
  'DB Schenker',
  'Geodis',
  'Maersk',
  'Hapag-Lloyd',
  'Prologis',

  // ─── HR & TALENT ────────────────────────────────────────────────────────────
  'ADP',
  'Ceridian',
  'Paychex',
  'UKG',
  'Cornerstone OnDemand',
  'Greenhouse',
  'Lever',
  'iCIMS',
  'LinkedIn',
  'Indeed',
  'Glassdoor',
  'ZipRecruiter',
  'Robert Half',
  'Manpower',
  'Adecco',
  'Randstad',
  'Korn Ferry',
  'Spencer Stuart',
  'Egon Zehnder',
  'Heidrick & Struggles',
  'Russell Reynolds',

  // ─── EDUCATION ──────────────────────────────────────────────────────────────
  'Coursera',
  'edX',
  'Udemy',
  'Khan Academy',
  'Chegg',
  'Pearson',
  'McGraw-Hill',
  '2U',
  'Duolingo',

  // ─── INDUSTRIALS ────────────────────────────────────────────────────────────
  'General Electric',
  'Honeywell',
  '3M',
  'Emerson Electric',
  'Eaton',
  'Parker Hannifin',
  'Illinois Tool Works',
  'Danaher',
  'Roper Technologies',
  'Dover',
  'Xylem',
  'Caterpillar',
  'Deere & Company',
  'John Deere',
];
