/**
 * Curated list of ~700 job titles derived from O*NET SOC classifications.
 * Used for client-side autocomplete in the Role Catalog search.
 */
export const JOB_TITLES: string[] = [
  // ─── SOFTWARE ENGINEERING ───────────────────────────────────────────────────
  'Software Engineer',
  'Junior Software Engineer',
  'Mid-Level Software Engineer',
  'Senior Software Engineer',
  'Staff Software Engineer',
  'Principal Software Engineer',
  'Distinguished Engineer',
  'Software Engineer II',
  'Software Engineer III',
  'Lead Software Engineer',
  'Software Development Engineer',
  'SDE I',
  'SDE II',
  'SDE III',
  'Senior SDE',
  'Principal SDE',
  'Software Developer',
  'Application Developer',
  'Full Stack Developer',
  'Full Stack Engineer',
  'Senior Full Stack Engineer',
  'Frontend Developer',
  'Frontend Engineer',
  'Senior Frontend Engineer',
  'Staff Frontend Engineer',
  'Principal Frontend Engineer',
  'Backend Developer',
  'Backend Engineer',
  'Senior Backend Engineer',
  'Staff Backend Engineer',
  'Principal Backend Engineer',
  'iOS Developer',
  'iOS Engineer',
  'Senior iOS Engineer',
  'Staff iOS Engineer',
  'Android Developer',
  'Android Engineer',
  'Senior Android Engineer',
  'Staff Android Engineer',
  'Mobile Developer',
  'Mobile Engineer',
  'Senior Mobile Engineer',
  'React Native Developer',
  'Flutter Developer',
  'Embedded Software Engineer',
  'Firmware Engineer',
  'Systems Software Engineer',
  'Systems Engineer',
  'Low-Latency Engineer',
  'Distributed Systems Engineer',
  'API Engineer',
  'Integration Engineer',
  'Middleware Engineer',
  'Graphics Engineer',
  'Game Developer',
  'Game Engineer',
  'Simulation Engineer',

  // ─── PLATFORM / INFRA / DEVOPS / SRE ───────────────────────────────────────
  'Platform Engineer',
  'Senior Platform Engineer',
  'Staff Platform Engineer',
  'Infrastructure Engineer',
  'Senior Infrastructure Engineer',
  'Site Reliability Engineer',
  'SRE',
  'Senior SRE',
  'Staff SRE',
  'Principal SRE',
  'DevOps Engineer',
  'Senior DevOps Engineer',
  'Staff DevOps Engineer',
  'Cloud Engineer',
  'Senior Cloud Engineer',
  'Cloud Infrastructure Engineer',
  'Cloud Solutions Engineer',
  'Kubernetes Engineer',
  'MLOps Engineer',
  'DataOps Engineer',
  'Build Engineer',
  'Release Engineer',
  'Build & Release Engineer',
  'Developer Experience Engineer',
  'DevEx Engineer',
  'Reliability Engineer',

  // ─── ENGINEERING MANAGEMENT ─────────────────────────────────────────────────
  'Engineering Manager',
  'Senior Engineering Manager',
  'Director of Engineering',
  'VP of Engineering',
  'SVP of Engineering',
  'Head of Engineering',
  'CTO',
  'Chief Technology Officer',

  // ─── ARCHITECTURE ───────────────────────────────────────────────────────────
  'Solutions Architect',
  'Enterprise Architect',
  'Cloud Architect',
  'Software Architect',
  'Application Architect',
  'Technical Architect',
  'Principal Architect',
  'Chief Architect',

  // ─── DATA SCIENCE & ML ──────────────────────────────────────────────────────
  'Data Scientist',
  'Senior Data Scientist',
  'Staff Data Scientist',
  'Principal Data Scientist',
  'Lead Data Scientist',
  'Machine Learning Engineer',
  'Senior Machine Learning Engineer',
  'Staff Machine Learning Engineer',
  'Principal Machine Learning Engineer',
  'ML Engineer',
  'AI Engineer',
  'Senior AI Engineer',
  'AI Research Scientist',
  'Applied Scientist',
  'Research Scientist',
  'NLP Engineer',
  'Natural Language Processing Engineer',
  'Computer Vision Engineer',
  'Deep Learning Engineer',
  'Reinforcement Learning Engineer',
  'ML Platform Engineer',
  'Research Engineer',
  'AI Safety Researcher',
  'Responsible AI Engineer',
  'Recommendation Systems Engineer',
  'Search Engineer',
  'Ranking Engineer',
  'Knowledge Graph Engineer',
  'Quantitative Researcher',

  // ─── DATA ENGINEERING & ANALYTICS ──────────────────────────────────────────
  'Data Engineer',
  'Senior Data Engineer',
  'Staff Data Engineer',
  'Principal Data Engineer',
  'Lead Data Engineer',
  'Analytics Engineer',
  'Data Analyst',
  'Senior Data Analyst',
  'Lead Data Analyst',
  'Principal Data Analyst',
  'Business Intelligence Analyst',
  'BI Developer',
  'BI Engineer',
  'Data Visualization Engineer',
  'Data Warehouse Engineer',
  'ETL Developer',
  'ETL Engineer',
  'Quantitative Analyst',
  'Quant Developer',

  // ─── SECURITY & COMPLIANCE ──────────────────────────────────────────────────
  'Security Engineer',
  'Senior Security Engineer',
  'Staff Security Engineer',
  'Cybersecurity Engineer',
  'Application Security Engineer',
  'Cloud Security Engineer',
  'Network Security Engineer',
  'Security Analyst',
  'Senior Security Analyst',
  'Penetration Tester',
  'Ethical Hacker',
  'Red Team Engineer',
  'Blue Team Engineer',
  'Threat Intelligence Analyst',
  'SOC Analyst',
  'Security Operations Center Analyst',
  'Incident Response Engineer',
  'Forensics Analyst',
  'Identity and Access Management Engineer',
  'IAM Engineer',
  'Compliance Engineer',
  'GRC Analyst',
  'Security Architect',
  'CISO',
  'Chief Information Security Officer',
  'VP of Security',
  'Head of Security',
  'DevSecOps Engineer',

  // ─── QA / TESTING ───────────────────────────────────────────────────────────
  'QA Engineer',
  'Quality Assurance Engineer',
  'Senior QA Engineer',
  'SDET',
  'Software Development Engineer in Test',
  'Test Automation Engineer',
  'Quality Engineer',
  'Performance Engineer',
  'Load Testing Engineer',
  'Accessibility Engineer',

  // ─── PRODUCT MANAGEMENT ─────────────────────────────────────────────────────
  'Product Manager',
  'Senior Product Manager',
  'Staff Product Manager',
  'Principal Product Manager',
  'Group Product Manager',
  'Director of Product Management',
  'VP of Product',
  'SVP of Product',
  'Chief Product Officer',
  'CPO',
  'Head of Product',
  'Technical Product Manager',
  'Platform Product Manager',
  'Growth Product Manager',
  'Data Product Manager',
  'Consumer Product Manager',
  'Enterprise Product Manager',
  'B2B Product Manager',
  'B2C Product Manager',
  'Product Owner',
  'Product Lead',
  'Associate Product Manager',
  'APM',
  'Product Strategy Manager',

  // ─── DESIGN & UX ────────────────────────────────────────────────────────────
  'UX Designer',
  'Senior UX Designer',
  'Lead UX Designer',
  'Principal UX Designer',
  'UI Designer',
  'Senior UI Designer',
  'Product Designer',
  'Senior Product Designer',
  'Staff Product Designer',
  'UX Researcher',
  'Senior UX Researcher',
  'Research Lead',
  'Design Researcher',
  'Visual Designer',
  'Interaction Designer',
  'Motion Designer',
  'Design Systems Engineer',
  'Brand Designer',
  'Creative Director',
  'Art Director',
  'Head of Design',
  'VP of Design',
  'Chief Design Officer',
  'UX Writer',
  'Content Designer',
  'Information Architect',
  'Accessibility Designer',

  // ─── PROGRAM & PROJECT MANAGEMENT ───────────────────────────────────────────
  'Technical Program Manager',
  'Senior Technical Program Manager',
  'Staff Technical Program Manager',
  'Principal Technical Program Manager',
  'Program Manager',
  'Senior Program Manager',
  'Director of Program Management',
  'VP of Program Management',
  'Head of PMO',
  'Project Manager',
  'Senior Project Manager',
  'Scrum Master',
  'Agile Coach',
  'Release Manager',
  'Portfolio Manager',
  'IT Project Manager',
  'Digital Transformation Program Manager',

  // ─── FINANCE & ACCOUNTING ───────────────────────────────────────────────────
  'Financial Analyst',
  'Senior Financial Analyst',
  'Finance Manager',
  'Senior Finance Manager',
  'Director of Finance',
  'VP of Finance',
  'SVP of Finance',
  'CFO',
  'Chief Financial Officer',
  'FP&A Analyst',
  'FP&A Manager',
  'Director of FP&A',
  'Controller',
  'Assistant Controller',
  'Chief Accounting Officer',
  'Accountant',
  'Senior Accountant',
  'CPA',
  'Tax Analyst',
  'Tax Manager',
  'Director of Tax',
  'Treasury Analyst',
  'Treasury Manager',
  'Investment Analyst',
  'Investment Associate',
  'Portfolio Manager',
  'Fund Manager',
  'Fixed Income Analyst',
  'Equity Research Analyst',
  'Risk Analyst',
  'Credit Analyst',
  'Credit Risk Manager',
  'Market Risk Analyst',
  'Operational Risk Manager',
  'Financial Controller',
  'M&A Analyst',
  'M&A Associate',
  'Investment Banking Analyst',
  'Investment Banking Associate',
  'Investment Banking Vice President',
  'Managing Director',
  'Private Equity Analyst',
  'Venture Capital Analyst',
  'Growth Equity Associate',
  'Hedge Fund Analyst',
  'Actuarial Analyst',
  'Actuary',
  'Financial Advisor',
  'Wealth Manager',
  'Financial Planner',

  // ─── MARKETING ──────────────────────────────────────────────────────────────
  'Marketing Manager',
  'Senior Marketing Manager',
  'Director of Marketing',
  'VP of Marketing',
  'SVP of Marketing',
  'CMO',
  'Chief Marketing Officer',
  'Head of Marketing',
  'Brand Manager',
  'Senior Brand Manager',
  'Product Marketing Manager',
  'Senior Product Marketing Manager',
  'Director of Product Marketing',
  'VP of Product Marketing',
  'Content Strategist',
  'Content Marketing Manager',
  'SEO Specialist',
  'SEO Manager',
  'SEM Manager',
  'Paid Media Manager',
  'Performance Marketing Manager',
  'Growth Marketing Manager',
  'Director of Growth',
  'VP of Growth',
  'Head of Growth',
  'Social Media Manager',
  'Social Media Strategist',
  'Community Manager',
  'Email Marketing Manager',
  'CRM Manager',
  'Marketing Analyst',
  'Demand Generation Manager',
  'Lead Generation Manager',
  'Field Marketing Manager',
  'Event Marketing Manager',
  'Partnership Marketing Manager',
  'Influencer Marketing Manager',
  'Copywriter',
  'Senior Copywriter',
  'Brand Strategist',
  'Market Research Analyst',
  'Consumer Insights Analyst',

  // ─── SALES ──────────────────────────────────────────────────────────────────
  'Sales Development Representative',
  'SDR',
  'Account Executive',
  'Senior Account Executive',
  'Enterprise Account Executive',
  'Strategic Account Executive',
  'Sales Engineer',
  'Solutions Engineer',
  'Sales Manager',
  'Regional Sales Manager',
  'Director of Sales',
  'VP of Sales',
  'SVP of Sales',
  'Chief Revenue Officer',
  'CRO',
  'Head of Sales',
  'Account Manager',
  'Key Account Manager',
  'Inside Sales Representative',
  'Field Sales Representative',
  'Business Development Representative',
  'BDR',
  'Business Development Manager',
  'Director of Business Development',
  'Partnership Manager',
  'Channel Sales Manager',
  'Customer Success Manager',
  'Senior Customer Success Manager',
  'Director of Customer Success',
  'VP of Customer Success',
  'Revenue Operations Manager',
  'Sales Operations Analyst',

  // ─── OPERATIONS & SUPPLY CHAIN ──────────────────────────────────────────────
  'Operations Manager',
  'Senior Operations Manager',
  'Director of Operations',
  'VP of Operations',
  'COO',
  'Chief Operating Officer',
  'Head of Operations',
  'Business Operations Manager',
  'Supply Chain Manager',
  'Senior Supply Chain Manager',
  'Director of Supply Chain',
  'VP of Supply Chain',
  'Supply Chain Analyst',
  'Procurement Manager',
  'Strategic Sourcing Manager',
  'Category Manager',
  'Vendor Manager',
  'Logistics Manager',
  'Distribution Manager',
  'Warehouse Manager',
  'Inventory Manager',
  'Demand Planner',
  'Supply Planner',
  'Production Manager',
  'Manufacturing Engineer',
  'Industrial Engineer',
  'Quality Manager',
  'Six Sigma Black Belt',
  'Lean Specialist',
  'Continuous Improvement Manager',
  'Process Improvement Manager',
  'Facilities Manager',

  // ─── HUMAN RESOURCES ────────────────────────────────────────────────────────
  'HR Business Partner',
  'Senior HR Business Partner',
  'HR Manager',
  'Senior HR Manager',
  'Director of Human Resources',
  'VP of Human Resources',
  'CHRO',
  'Chief Human Resources Officer',
  'Head of People',
  'People Operations Manager',
  'Recruiter',
  'Technical Recruiter',
  'Senior Recruiter',
  'Talent Acquisition Manager',
  'Director of Talent Acquisition',
  'VP of Talent Acquisition',
  'Head of Talent',
  'Recruiting Coordinator',
  'Compensation Analyst',
  'Compensation Manager',
  'Benefits Manager',
  'Total Rewards Manager',
  'Learning & Development Manager',
  'L&D Specialist',
  'Training Manager',
  'Organizational Development Manager',
  'HR Generalist',
  'HRIS Analyst',
  'Workforce Planning Analyst',
  'Diversity & Inclusion Manager',
  'Employee Relations Manager',

  // ─── CONSULTING ─────────────────────────────────────────────────────────────
  'Management Consultant',
  'Senior Consultant',
  'Engagement Manager',
  'Associate Principal',
  'Principal Consultant',
  'Strategy Consultant',
  'Business Analyst',
  'Senior Business Analyst',
  'Technology Consultant',
  'Digital Transformation Consultant',
  'Change Management Consultant',
  'IT Consultant',
  'Organization Design Consultant',

  // ─── HEALTHCARE ─────────────────────────────────────────────────────────────
  'Medical Affairs Manager',
  'Clinical Research Associate',
  'Clinical Trial Manager',
  'Regulatory Affairs Specialist',
  'Healthcare Product Manager',
  'Health Informatics Manager',
  'Clinical Data Manager',
  'Pharmacovigilance Specialist',
  'Medical Science Liaison',
  'Hospital Administrator',
  'Healthcare Operations Manager',
  'Chief Medical Officer',
  'Patient Experience Manager',
  'Health Technology Analyst',
  'Biotech Analyst',
  'Drug Safety Specialist',
  'Quality Assurance Specialist',
  'Regulatory Affairs Manager',

  // ─── LEGAL ──────────────────────────────────────────────────────────────────
  'Corporate Counsel',
  'In-House Counsel',
  'General Counsel',
  'Associate General Counsel',
  'Chief Legal Officer',
  'Compliance Manager',
  'Compliance Officer',
  'Chief Compliance Officer',
  'Privacy Counsel',
  'Data Privacy Officer',
  'DPO',
  'Contract Manager',
  'Legal Operations Manager',
  'IP Counsel',

  // ─── EXECUTIVE ──────────────────────────────────────────────────────────────
  'Chief Executive Officer',
  'CEO',
  'President',
  'General Manager',
  'Executive Director',
  'Managing Director',
  'Chief Information Officer',
  'CIO',
  'Chief Data Officer',
  'CDO',
  'Chief Analytics Officer',
  'Chief Digital Officer',
  'Chief Innovation Officer',
  'Chief Strategy Officer',
];
