export interface KeywordItem {
  id: string;
  word: string;
  // Widened to string so AI-generated profiles can use any category label
  category: string;
  added: boolean;
  isStaged?: boolean;
  isNewFlash?: boolean;
}

export interface FluffItem {
  word: string;
  category: 'Vague Claim' | 'Corporate Jargon' | 'Passive Voice' | 'Overused Buzzword';
  impact: 'High' | 'Medium' | 'Low';
  explanation: string;
  suggestedMetricSwap: string;
}

export interface FluffMatch extends FluffItem {
  id: string;
  count: number;
}

export interface StarQuestion {
  id: string;
  question: string;
  gapContext: string;
  difficulty: 'Staff' | 'Lead' | 'Executive';
  situationKeywords: string[];
  taskKeywords: string[];
  actionKeywords: string[];
  resultKeywords: string[];
}

export interface StarProgress {
  situation: boolean;
  task: boolean;
  action: boolean;
  result: boolean;
}

export interface PresetProfile {
  id: string;
  name: string;
  // Widened to string so AI-generated profiles aren't limited to 6 values
  industry: string;
  targetRole: string;
  company: string;
  matchScoreBaseline: number;
  defaultResume: string;
  defaultJobDescription: string;
  missingKeywords: KeywordItem[];
  fluffDictionary: FluffItem[];
  starQuestions: StarQuestion[];
  /** True when this profile was generated by AI rather than loaded from presets */
  isAiGenerated?: boolean;
}

export type AnalysisStep = 'idle' | 'parsing' | 'keywords' | 'ats' | 'complete';
